name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
    - name: Pull repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{secrets.REGISTRY_USERNAME}}
        password: ${{secrets.REGISTRY_PASSWORD}}
        login-server: https://index.docker.io/v1/

    - name: Run CICD script
      run: |
        # Get commited dockerfiles.
        files=$(git log -1 --stat --name-only | grep Dockerfile)
        # If not dockerfiles exit
        if [ -z "$files" ] 
        then
          exit 0

        # Iterate each new Dockerfile/image
        for file in $files
        do
          # Use name of Dockerfile parent folder as Toolkit name.
          toolkit=$(basename $(dirname $file))
          #Build and push each image
          docker build -f $file -t vicsufer/tools:$toolkit $(dirname file)
          docker push vicsufer/tools:$toolkit
        done
      shell: bash

